// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChwQO5oSojcto5ZhWkvY-IzdJC-JE9j18',
    appId: '1:867987530241:web:ff757495ca5f7287111600',
    messagingSenderId: '867987530241',
    projectId: 'chessapp-e8234',
    authDomain: 'chessapp-e8234.firebaseapp.com',
    storageBucket: 'chessapp-e8234.firebasestorage.app',
    measurementId: 'G-48GQ60BKNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZyuR2n1vJtF6PtR2fhYRqQ2QYKwnt4IA',
    appId: '1:867987530241:android:f6598880e3ab305f111600',
    messagingSenderId: '867987530241',
    projectId: 'chessapp-e8234',
    storageBucket: 'chessapp-e8234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtR1YvdoJPooiL_2QUq6GjKbKt5Moci34',
    appId: '1:867987530241:ios:3a768f606325bd6f111600',
    messagingSenderId: '867987530241',
    projectId: 'chessapp-e8234',
    storageBucket: 'chessapp-e8234.firebasestorage.app',
    iosBundleId: 'com.example.chessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtR1YvdoJPooiL_2QUq6GjKbKt5Moci34',
    appId: '1:867987530241:ios:3a768f606325bd6f111600',
    messagingSenderId: '867987530241',
    projectId: 'chessapp-e8234',
    storageBucket: 'chessapp-e8234.firebasestorage.app',
    iosBundleId: 'com.example.chessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChwQO5oSojcto5ZhWkvY-IzdJC-JE9j18',
    appId: '1:867987530241:web:3e4e59634553cd48111600',
    messagingSenderId: '867987530241',
    projectId: 'chessapp-e8234',
    authDomain: 'chessapp-e8234.firebaseapp.com',
    storageBucket: 'chessapp-e8234.firebasestorage.app',
    measurementId: 'G-HTXGBNFZ5Q',
  );
}
